### ISSUE TITLE
Sakura - Havoc OS 4.5 just switches off

### ISSUE THREAD

**Issue by arpitphillips** [Havoc-OS/Devices#37]
Hello! So I'm facing an issue where the phone just dies randomly, sometimes while it's not being used, occasionally while being used too - such as in the middle of a phone call. After this I have to manually boot (reason for edit: I had written reboot, however it's in a powered down state already and I have to power it on) the device.

I've tried flashing after wiping all the options in the recovery, tried factory resetting and simply flashing over the current installation of the same.
Device is sakura.
Havoc OS version is 4.5

I've just clean flashed again without GApps this time, and will update if this happens again.

Will it help if I take a logcat after the phone turns off?

**Comment by OmlineEditor** [comment]
they won't help you here, you need to look for another place to help. look, they don't even answer questions here, they just close tickets
