### ISSUE TITLE
Galaxy A8 2018

### ISSUE THREAD

**Issue by CrazyWolf13** [Havoc-OS/Devices#56]
Hello there, 
I'm not sure where i should post this. 

Somenone in the XDA Discord told me about Havoc OS and since i installed it on my galaxy a3 2016, which now nearly runs smoother than my galaxy a8 from 2018 . I'm stunned and amazed by you guys, keep this work up.

So to my questions, do you consider adding the galaxy a8 2018 to your supported devices? Cause the GSI wouldn't run (image to big) And sadly there are very less Custom ROMS for my phone.

This would really make me happy.
Have a nice day.
Crazy_Saft

**Comment by SukeeratSG** [comment]
There is an procedure for official maintainers to apply and add devices to our device roster.
We aren't able to handle builds for devices which nobody in our organization has.

**Comment by CrazyWolf13** [comment]
Okay no problem, thanks for answering anyways

**Comment by SukeeratSG** [comment]
No problem <3
